{
 "title": "FastDFS Monitor",
 "description": "fastdfs exporter dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasoucre", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(fastdfs_tracker_server_info, instance) "
   },
   {
    "name": "tracker",
    "query": "label_values(fastdfs_tracker_server_info{instance=~\"$instance\"}, tracker) "
   },
   {
    "name": "group",
    "query": "label_values(fastdfs_group_info{instance=~\"$instance\"}, group) "
   },
   {
    "name": "storage",
    "query": "label_values(fastdfs_storage_server_info{instance=~\"$instance\",group=~\"$group\"}, storage) "
   }
  ]
 },
 "panels": [
  { "title": "TRACKER SERVER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasoucre" },
  {
   "title": "运行状态：$tracker",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "tracker",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_tracker_server_info{instance=~\"$instance\",tracker=~\"$tracker\"}"
    }
   ]
  },
  {
   "title": "运行状态：$tracker",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_tracker_server_info{instance=~\"$instance\",tracker=~\"$tracker\"}"
    }
   ]
  },
  { "title": "GROUP $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "group" },
  {
   "title": "运行状态：$storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_storage_server_info{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "repeat": "storage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastdfs_storage_version{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Jointime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "repeat": "storage",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_join_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "repeat": "storage",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_up_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：已用空间",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 5 },
   "repeat": "storage",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1-((fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}) / (fastdfs_total_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"})))* 100",
     "legendFormat": "{{storage}} "
    }
   ]
  },
  {
   "title": "运行状态：$storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_storage_server_info{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastdfs_storage_version{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Jointime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_join_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_up_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：已用空间",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1-((fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}) / (fastdfs_total_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"})))* 100",
     "legendFormat": "{{storage}} "
    }
   ]
  },
  {
   "title": "$storage：上传文件 ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：下载文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：删除文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：可用空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "repeat": "storage",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：上传文件 ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：下载文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：删除文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：可用空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage 文件操作失败曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "repeat": "storage",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fastdfs_total_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：上传失败文件"
    },
    {
     "expr": "fastdfs_total_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：下载失败文件"
    },
    {
     "expr": "fastdfs_total_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：删除失败文件"
    }
   ]
  },
  {
   "title": "$storage 文件操作失败曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fastdfs_total_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：上传失败文件"
    },
    {
     "expr": "fastdfs_total_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：下载失败文件"
    },
    {
     "expr": "fastdfs_total_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：删除失败文件"
    }
   ]
  },
  { "title": "GROUP $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "运行状态：$storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_storage_server_info{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 24 },
   "repeat": "storage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastdfs_storage_version{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Jointime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 24 },
   "repeat": "storage",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_join_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 24 },
   "repeat": "storage",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_up_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：已用空间",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 24 },
   "repeat": "storage",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1-((fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}) / (fastdfs_total_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"})))* 100",
     "legendFormat": "{{storage}} "
    }
   ]
  },
  {
   "title": "运行状态：$storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_storage_server_info{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastdfs_storage_version{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Jointime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_join_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - fastdfs_up_time{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：已用空间",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1-((fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}) / (fastdfs_total_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"})))* 100",
     "legendFormat": "{{storage}} "
    }
   ]
  },
  {
   "title": "$storage：上传文件 ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：下载文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：删除文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
   "repeat": "storage",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：可用空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "repeat": "storage",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage：上传文件 ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：下载文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{group}}@{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：删除文件",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "$storage：可用空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 33 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "fastdfs_free_storage{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}"
    }
   ]
  },
  {
   "title": "$storage 文件操作失败曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "repeat": "storage",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fastdfs_total_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：上传失败文件"
    },
    {
     "expr": "fastdfs_total_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：下载失败文件"
    },
    {
     "expr": "fastdfs_total_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：删除失败文件"
    }
   ]
  },
  {
   "title": "$storage 文件操作失败曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fastdfs_total_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_upload_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：上传失败文件"
    },
    {
     "expr": "fastdfs_total_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_download_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：下载失败文件"
    },
    {
     "expr": "fastdfs_total_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"} - fastdfs_success_delete_count{instance=~\"$instance\",group=~\"$group\",storage=~\"$storage\"}",
     "legendFormat": "{{storage}}：删除失败文件"
    }
   ]
  }
 ]
}